pipeline:
  name: Testing_pipeline
  identifier: Testing_pipeline
  projectIdentifier: My_First_CI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Harness
        build: <+input>
  stages:
    - stage:
        name: build stage
        identifier: build_stage
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: Harness
                    build:
                      type: branch
                      spec:
                        branch: My_testing_branch
              - step:
                  type: Run
                  name: Maven Build
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: mvn clean install
